### ISSUE TITLE
Title in templates like set in extension module

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Eternizer#60]

**Comment by Portugao** [comment]
Fixed with f98d3cf

**Comment by Guite** [comment]
Maybe something for the generator?

**Comment by Portugao** [comment]
Yes, that would be helpful.

**Comment by Portugao** [comment]
This is fixed by generator fix:
https://github.com/Guite/MostGenerator/commit/f713df706b838b4afa89ebd5e51847a415431abb
